layout: ""
url: "https://opnay.com"

permalink: /:categories/:year:month-:slug

defaults:
  -
    scope:
      path: ""
    values:
      image_number: 6
      md_theme:
        main: "#2196F3"
        light: "#6ec6ff"
        dark: "#0069c0"
