layout: ""
title: "OPNay Studio"
url: "https://opnay.com"

permalink: /:categories/:year:month-:slug

exclude: ["CNAME","README.md"]

# Opengraph
twitter: "@opnay_dev"

defaults:
  -
    scope:
      path: ""
    values:
      image_number: 6
      md_theme:
        main: "#2196F3"
        light: "#6ec6ff"
        dark: "#0069c0"
      img_background: true
  -
    scope:
      path: "_posts"
    values:
      layout: 'blog'
      comments: true
      ads: true
  -
    scope:
      path: 'category'
    values:
      layout: 'category'
      back: '/category'