name: Deploy Blog

on:
  push:
    branches:
      - gatsby
      - gatsby-action

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install Packages
      run: npm install
      env:
        CI: true
        
    - name: Build Gatsby 
      run: npm run build
        
    - name: Push to master
      uses: maxheld83/ghpages@master
      with:
        BUILD_DIR: public
        GH_PAT: ${{ secrets.GITHUB_TOKEN }}
