name: Node CI

on:
  push:
    branches:
      - gatsby
      - gatsby-action

jobs:
  initial:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install
      run: npm install
      env:
        CI: true
