name: Deploy Blog

on:
  push:
    branches:
      - gatsby
      - gatsby-action

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install Packages
      run: npm install
      env:
        CI: true
        
    - name: Build Gatsby 
      run: npm run build
        
    - name: Push to master
      run: |
        chmod a+x ./.github/scripts/*.sh
        ./.github/scripts/push.sh
      env:
        BUILD_DIR: public
        TOKEN: ${{ secrets.TOKEN }}
